### ISSUE TITLE
RUNE Broadcast error 

### ISSUE THREAD

**Issue by Wangmmx** [thorchain/thornode#4]
Hi, I tried to send RUNE but got this error:Error: failed to execute message; message index: 0: rune transfers are currently disabled: send transactions are disabled, could you please help me with this?
It cost fee but no RUNE sent successfully

**Comment by LXHLeaner** [comment]
> Hi, I tried to send RUNE but got this error:Error: failed to execute message; message index: 0: rune transfers are currently disabled: send transactions are disabled, could you please help me with this? It cost fee but no RUNE sent successfully

I have a very difficult problem，you have sent RUNE success by using the [thornode](https://github.com/thorchain/thornode) ?

**Comment by Wangmmx** [comment]
> > Hi, I tried to send RUNE but got this error:Error: failed to execute message; message index: 0: rune transfers are currently disabled: send transactions are disabled, could you please help me with this? It cost fee but no RUNE sent successfully
> 
> I have a very difficult problem，you have sent RUNE success by using the [thornode](https://github.com/thorchain/thornode) ?

I have sent at last, maybe it was fixed, close it now

**Comment by Iqbalqwerty** [comment]
Subject: Urgent: Stuck THORChain Transaction – Outbound Not Signed

Dear THORChain Support Team,

I recently performed a swap on THORChain using Trust Wallet, but my transaction is stuck. The current status shows:

Inbound: Success ✅

Refund Swap: Error ⚠️

Outbound: Pending – Not Signed ⏳

Estimated Schedule: Passed


Transaction Details:

Transaction ID (TxID): b9d70ea425c44ce0a2f78ea0bdb2fc861e214d93752bc9a1f811000dc2b44d4b

Swapped From: Bitcoin (BTC)

Swapped To: Binance Coin (BNB)

Platform Used: Trust Wallet


My BTC transaction has already been confirmed on the Bitcoin network (verified via mempool.space), but the outbound refund transaction has not been signed and is delayed beyond the estimated schedule.

I kindly request your assistance in processing this transaction or signing the refund manually if necessary. Your urgent support is greatly appreciated.

Looking forward to your response.

Best regards,
Danish Iqbal
